### ISSUE TITLE
ReplyAsync is not found

### ISSUE THREAD

**Issue by rikashore** [Discord-Net-Labs/Discord.Net-Labs#1]
Upon trying to use `ReplyAsync` within a command module, I'm hit with an error stating that the method is not found, using the `SendMessageFunction` on the channel however works as intended.

**Comment by quinchs** [comment]
Is this using Discord.Net.Commands?

**Comment by rikashore** [comment]
yes, its using Discord.Commands although the ReplyAsync is the method on the context

**Comment by quinchs** [comment]
Are you using the labs version of Discord.Net.Commands?

**Comment by rikashore** [comment]
I probably am not, Yeah I might have to do that, thanks again
