### ISSUE TITLE
Update to include context menus

### ISSUE THREAD

**Issue by MrCakeSlayer** [Discord-Net-Labs/Discord.Net-Labs#103]
Docs reference: https://discord.com/developers/docs/interactions/application-commands#user-commands

Types:
- [x] [CHAT_INPUT](https://discord.com/developers/docs/interactions/application-commands#slash-commands) - 1 - Slash commands; a text-based command that shows up when a user types `/`
- [x] [USER](https://discord.com/developers/docs/interactions/application-commands#user-commands)             - 2 - A UI-based command that shows up when you right click or tap on a user
- [x] [MESSAGE](https://discord.com/developers/docs/interactions/application-commands#message-commands)      - 3 - A UI-based command that shows up when you right click or tap on a messages

While CHAT_INPUT requires command names to match `^[\w-]{1,32}$`, USER and MESSAGE names can be fixed cased and can include spaces.

Unlike CHAT_INPUT, the other types do not allow the description to be set when creating the command. (and return an empty string instead of null for backward compatibility.)

Also note, you can only create 5 of each MESSAGE or USER command types. (Compared to the 100 of CHAT_INPUT)

**Comment by drobbins329** [comment]
Submitted PR for create/modify/delete of guild/global slash/user/message commands.

**Comment by drobbins329** [comment]
can this be marked as closed?
