### ISSUE TITLE
Add DiscordSocketClient.SetAboutMeAsync()

### ISSUE THREAD

**Issue by csmir** [Discord-Net-Labs/Discord.Net-Labs#108]
Several bots make use of this feature to provide additional information to their bots. It would be much appreciated if we could do so as well through a DiscordSocketClient method. 
![Example](https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/rozen/Share/Discord_6fVIuC9ufz.png)

**Comment by d4n3436** [comment]
It seems that bots [cannot change their description](https://github.com/discord/discord-api-docs/discussions/3574#discussioncomment-1127822) via the API, but you can manually edit it in the [dev portal](https://discord.com/developers/applications).

**Comment by csmir** [comment]
Understood, I made an assumption that this would be possible as any other general 'profile setting'.
