### ISSUE TITLE
Make SocketUser.BannerId nullable and state it as nullable in xml

### ISSUE THREAD

**Issue by csmir** [Discord-Net-Labs/Discord.Net-Labs#112]
Discord Documentation states that bannerid should and can be nullable, while dnetlabs does not recieve it as such. This change would provide a check to display a banner or not. 
![see](https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/rozen/Share/msedge_KZaWLQqxpw.png)

**Comment by csmir** [comment]
Adding to this, ` user.GetBannerUrl(); ` will always return null, even if the user has a banner. This should not be the case? I tried several user types, and several different users to debug this. The local string is always null.

**Comment by csmir** [comment]
![see](https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/rozen/Share/devenv_3hvSBmvinI.png) 

![see](https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/rozen/Share/Discord_AVigidpOFP.png)

**Comment by quinchs** [comment]
Changing whether its nullable or not has 0 effect, the issue is that discord doesnt reeturn in over websocket, take a look at this:
```cs
                var user = await client.Rest.GetUserAsync(259053800755691520);
                var socketUser = client.GetUser(259053800755691520);
                var restId = user.BannerId;
                var socketId = socketUser.BannerId;
```
`restId` is the banner id while `socketId` is null. We can go further and take a look at the json we got from discord

**Websocket**
```json
{
         "user":{
            "username":"quin",
            "public_flags":256,
            "id":"259053800755691520",
            "discriminator":"3017",
            "avatar":"1b1a1c1a62756406ebb3319138e08d4b"
         },
         "roles":[
            "848547175361413121",
            "848176625333436436",
            "848547101054730260",
            "870789641186443284",
            "848176387029991434",
            "848176903608336395"
         ],
         "premium_since":"2021-07-30T19:07:08.797-03:00",
         "pending":false,
         "nick":"quinch",
         "mute":false,
         "joined_at":"2021-05-29T09:29:28.277-03:00",
         "is_pending":false,
         "hoisted_role":"848176903608336395",
         "deaf":false,
         "avatar":null
      },
```

**Rest**:
```json
{
   "id":"259053800755691520",
   "username":"quin",
   "avatar":"1b1a1c1a62756406ebb3319138e08d4b",
   "discriminator":"3017",
   "public_flags":256,
   "banner":"4fe4c560f18bf71c5880f57d3693dea4",
   "banner_color":"#2c52d4",
   "accent_color":2904788
}
```

I don't know if this is intentional behavior or not, I can bring it up in the API server.

**Comment by csmir** [comment]
I can indeed verify that it does work for the rest user. I'll keep the other issue open (which directly mentions the get issue) and close this one.
