### ISSUE TITLE
SocketSlashCommand RespondAsync the "ephemeral" parameter is not applied on the first submission

### ISSUE THREAD

**Issue by ITilyaGO** [Discord-Net-Labs/Discord.Net-Labs#113]
I want to send an ephemeral message in response to a slash command, but this parameter has no effect on the message the first time it is sent. In this case, if you apply "RespondAsync()" to the "SocketSlashCommand" again, then the parameter will work correctly.

Function
```c#
public async Task SlashCommandHandler(SocketSlashCommand ssc)
        {
            if (ssc.Data.Name == "test")
            {
                await CommandTest(ssc);
            }else if (ssc.Data.Name == "help")
            {
                await ssc.RespondAsync(embed: null, text: "✅", ephemeral: true);
                await ssc.RespondAsync(embed: null, text: "✅", ephemeral: true);
                
            }
        }
```

result
![image](https://user-images.githubusercontent.com/42610063/130362827-dae5cd8a-1a14-4a78-8db7-83be310944a0.png)

1. How can I send an ephemeral message in response to a slash command?
2. _(off topic question)_How can I get an instance of a message sent through "RespondAsync" for example in the form "SocketUserMessage"?

**Comment by CottageDwellingCat** [comment]
make sure you have `AlwaysAcknowledgeInteractions` set to false in your `DiscordSocketConfig`, this will force you to respond to all interactions by deferring them (which you can do ephemerally) or responding to them within three seconds. If you do not that the client will say interaction failed. If an interaction is deferred you need to respond with `interaction.FollowupAsync` within fifteen minuets or the client will say the interaction failed. `RespondAsync` will result in an error being sent from the discord api if an interaction has been deferred.

sample client login code:
```cs
client = new DiscordSocketClient(new DiscordSocketConfig()
{
	AlwaysAcknowledgeInteractions = false,
});

await client.LoginAsync(TokenType.Bot, token);
await client.StartAsync();
```

sample interaction response code:
```cs
public async Task SlashCommandHandler(SocketSlashCommand ssc)
{
	if (ssc.Data.Name == "test")
	{
		await CommandTest(ssc);
	}
	else if (ssc.Data.Name == "help")
	{
		// optionally uncomment this line if your command response will take more than three seconds
		// the first bool determines if the response should be ephemeral
		// if the line is uncommented, you need to replace RespondAsync with FollowupAsync
		// ssc.DeferAsync(true);
		await ssc.RespondAsync(text: "my command responce", ephemeral: true);
	}
}
```

**Comment by Rutherther** [comment]
> _(off topic question)_How can I get an instance of a message sent through "RespondAsync" for example in the form "SocketUserMessage"?

By calling `SocketInteraction.GetOriginalResponseAsync` on the slash command interaction after you respond.
