### ISSUE TITLE
500 on CreateStickerAsync

### ISSUE THREAD

**Issue by quinchs** [Discord-Net-Labs/Discord.Net-Labs#115]
# Summary
Discord returns a 500 when creating a sticker via the [CreateGuildStickerAsync](https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/feature/stickers-expansion/src/Discord.Net.Rest/DiscordRestApiClient.cs#L921) method, by looking at how we send it. I'm not seeing an obvious issue, maybe someone could share a bit more light on it? 

Here's a working curl request just for examples sake:
```bash
curl --location --request POST 'https://discord.com/api/v9/guilds/848176216011046962/stickers' \
--header 'Authorization: Bot ODXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
--form 'name="test"' \
--form 'description="Testing"' \
--form 'tags="test, testing"' \
--form 'file=@"/C:/Users/USER/Pictures/image1.png"'
```

**Comment by d4n3436** [comment]
After some testing with curl and printing the raw http requests the lib sends to the console, I managed to find the problem.
Turns out the lib doesn't include a `Content-Type` header in the image being sent:

```
...

Content-Type: multipart/form-data; boundary="Upload----08/23/2021 16:57:48"

--Upload----08/23/2021 16:57:48
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=name

testname
--Upload----08/23/2021 16:57:48
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=description

testdescription
--Upload----08/23/2021 16:57:48
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=tags

tag1, tag2
--Upload----08/23/2021 16:57:48
(Missing Content-Type header)
Content-Disposition: form-data; name=file; filename=testname.png; filename*=utf-8''testname.png

(raw png)
--Upload----08/23/2021 16:57:48--
```

curl raw http request:

```
POST /api/v9/guilds/guild_id/stickers HTTP/1.1
Host: discord.com
User-Agent: curl/7.55.1
Accept: */*
Authorization: Bot ****
Content-Length: 609
Expect: 100-continue
Content-Type: multipart/form-data; boundary=------------------------c12f6a8cb49dc76f

--------------------------c12f6a8cb49dc76f
Content-Disposition: form-data; name="name"

testname
--------------------------c12f6a8cb49dc76f
Content-Disposition: form-data; name="description"

testdescription
--------------------------c12f6a8cb49dc76f
Content-Disposition: form-data; name="tags"

tag1, tag2
--------------------------c12f6a8cb49dc76f
Content-Disposition: form-data; name="file"; filename="testname.png"
Content-Type: application/octet-stream <--- curl adds the Content-Type

(raw png)
--------------------------c12f6a8cb49dc76f--
```

Adding the following code [here](https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/release/2.x/src/Discord.Net.Rest/Net/DefaultRestClient.cs#L119) fixes the issue:

```cs
var streamContent = new StreamContent(stream);
streamContent.Headers.ContentType = new MediaTypeHeaderValue("image/png"); // application/json for lottie?
content.Add(streamContent, p.Key, fileValue.Filename);
```

**Comment by SylveonDeko** [comment]
This was a discord side issue and can be safely closed as it was resolved.

**Comment by quinchs** [comment]
> This was a discord side issue and can be safely closed as it was resolved.

Is there a link to a thread about it?

**Comment by SylveonDeko** [comment]
Check the discord developer news channel

**Comment by quinchs** [comment]
"ability to gather images and other attachments from our CDN without specifying a User-Agent header.". This issue is for creating assets, and the content type is the issue

**Comment by SylveonDeko** [comment]
Right it's 8am in the morning and I need coffee to see.

**Comment by SylveonDeko** [comment]
My bad

**Comment by quinchs** [comment]
No worries

**Comment by d4n3436** [comment]
> This was a discord side issue and can be safely closed as it was resolved.

Even if this bug gets fixed, the API would just return an "Invalid Asset" error since the `Content-Type` header is required.

> Is there a link to a thread about it?

There's actually an [issue in discord-api-docs](https://github.com/discord/discord-api-docs/issues/3484) about this bug.
I guess Discord didn't fix this because it's a low priority bug (fixing it would just return a different error message).

**Comment by quinchs** [comment]
@d4n3436 Im noticing that the C# code doesnt chuck the string names within quotes while curl does
```
Content-Disposition: form-data; name=name
```
```
Content-Disposition: form-data; name="name"
```

Running your version produces this exception:
```cs
Discord.Net.HttpException: The server responded with error 50035: Invalid Form Body
{
  "name": {
    "_errors": [
      {
        "code": "BASE_TYPE_REQUIRED",
        "message": "This field is required"
      }
    ]
  },
  "tags": {
    "_errors": [
      {
        "code": "BASE_TYPE_REQUIRED",
        "message": "This field is required"
      }
    ]
  }
}
```

**Comment by d4n3436** [comment]
> Im noticing that the C# code doesnt chuck the string names within quotes while curl does

That's not really important. The API accepts parameters with no quotes.

> Running your version produces this exception:

Hmm that's weird. Are you using the code I sent at the bottom of my message?
It works for me (sorta), the API now returns a different error message:

```
{"message": "Maximum number of stickers reached (0)", "code": 30039}
```
Which makes sense since my test server doesn't have any sticker slots.

**Comment by quinchs** [comment]
Nvm i've fixed it, check the comit

**Comment by d4n3436** [comment]
I managed to confuse 2 people in a single issue mmlol

**Comment by quinchs** [comment]
Haha
