### ISSUE TITLE
Bot freezes when SetGameAsync for 3 times in a row in a short amount of time (5 seconds between changes).

### ISSUE THREAD

**Issue by xRoier** [Discord-Net-Labs/Discord.Net-Labs#117]
This happens in the latest version of Discord-Net-Labs, however this doesn't happens in v2.1.1 of the normal project (Discord.Net)

**Comment by quinchs** [comment]
Could you share your code, when are you setting the game? etc

**Comment by xRoier** [comment]
```
private async Task UpdateStatus(Bot Bot, string status)
{
    await Bot.Client.SetGameAsync(status);
    await Bot.Client.SetStatusAsync(status.StartsWith("0/")
        ? UserStatus.Idle
        : UserStatus.Online);
}
```
This is called every 5 seconds, this works perfectly fine in v2.1.1.

**Comment by MrCakeSlayer** [comment]
@xRoier are you still having this issue on the latest version?

**Comment by xRoier** [comment]
> @xRoier are you still having this issue on the latest version?

Didn't get a mail, sorry for the delay lol:
I didn't try, I'll try tomorrow.

**Comment by quinchs** [comment]
Any update?
