### ISSUE TITLE
Incorrect slash command name restrictions 

### ISSUE THREAD

**Issue by quinchs** [Discord-Net-Labs/Discord.Net-Labs#122]
In https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/release/3.x/src/Discord.Net.Core/Entities/Interactions/SlashCommandBuilder.cs there are multiple Regex.IsMatch(value, @"^[\w-]{3,32}$") is the minimum length of 3 correct? The Discord Docs indicate the minimum should be 1. ref https://discord.com/developers/docs/interactions/application-commands#application-command-object

**Comment by MrCakeSlayer** [comment]
I believe it was originally 3 when this was implemented and later dropped to 1
