### ISSUE TITLE
ulong used for RawValue of GuildPermissions

### ISSUE THREAD

**Issue by drobbins329** [Discord-Net-Labs/Discord.Net-Labs#126]
ulong is too short to get full permission list.
ulong is 32 bits, though per discord API, it stops at 37 bits.

https://docs.microsoft.com/en-us/cpp/cpp/integer-limits?view=msvc-160

**Comment by d4n3436** [comment]
> ulong is 32 bits

ulong is 64 bits

> https://docs.microsoft.com/en-us/cpp/cpp/integer-limits?view=msvc-160

That's from Microsoft's C++ docs, lol, you should see [C# docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types).

**Comment by drobbins329** [comment]
oops. but, the behavior i'm seeing is in line with the last few bits getting chopped. using latest 3.0.1 from nuget,
the following are all false. regardless of actual guild permissions:
Manage Threads
Request to Speak
Use External Stickers
Use Private Threads
Use Public Threads
Use Application Commands

all of them being beyond bit 32.

**Comment by drobbins329** [comment]
Only other thing I can think of is I'm using VS 2022.

**Comment by drobbins329** [comment]
found the issue. closing, and opening new.
