### ISSUE TITLE
The methods that respond to interactions should probably return an IMessage

### ISSUE THREAD

**Issue by arrendek** [Discord-Net-Labs/Discord.Net-Labs#144]
RespondAsync, CreateInteractionResponse, SendInteractionResponse and other methods which handle sending responses to an interaction currently return nothing, and they should probably return at least an IMessage.

I was looking for a way to get around the issue with UpdateAsync failing with a "10062: interaction not found" error from the Discord API. I was going to store the message id of the message with the components which are going out with RespondAsync to a slash command interaction (the same message I can't update with UpdateAsync) so that I could modify the message later when I noticed that the library doesn't return anything at all to the RespondAsync method.

I pulled the code from github and modified the path to return an IMessage. If you want I can submit a PR. Let me know.

Thanks.

**Comment by drobbins329** [comment]
Try FollowupAsync... it does return a message object. Respondasync, I believe, is meant to be a send and forget.

**Comment by arrendek** [comment]
I guess I misunderstood the purposes of the two methods Respond and Followup. Are they essentially the same?

**Comment by quinchs** [comment]
> Both act in a similar way, however if you have AlwaysAcknowledge set to false in your DiscordSocketConfig, your interactions will need to use RespondAsync for the first message to "acknowledge" the interaction, then you can send further messages with FollowupAsync.

Taken from the [discord server](https://discord.com/invite/dvSfUTet3K) in the [faq channel](https://discord.com/channels/848176216011046962/848185023781797908/848185797147623454).

`RespondAsync` sends a "Response" to the interaction, this is a one time message that is the initial reply to the event. Followups are whats written on the tin, they send another additional message for the interaction. The library will do some checks when using the `RespondAsync` method to see if you would have already responded via ack's and will automatically send a followup instead. Most of the time you rarely have to worry about the different methods.
