### ISSUE TITLE
Delete slash commands

### ISSUE THREAD

**Issue by Shadowtail117** [Discord-Net-Labs/Discord.Net-Labs#146]
A bot I am making has gone through a couple of revisions including the name of its slash commands. However, the old slash commands still exist and I am not sure how to delete them. Do I do so via the dev portal, or via methods? Is there a way to completely reset the bot's slash commands so they can be rebuilt?

**Comment by SylveonDeko** [comment]
theres a delete all endpoint, that way you can remake all slash commands

**Comment by Shadowtail117** [comment]
> theres a delete all endpoint, that way you can remake all slash commands

How would I use that?

**Comment by SylveonDeko** [comment]
as far as i remember, call your rest client and call DeleteSlashCommands, i may be wrong

**Comment by SylveonDeko** [comment]
ill verify in a sec

**Comment by killerfrienddk** [comment]
I think if you use the bulk update it will allow you to update all of them and remove old onces.
Here is an example on how to do it: https://github.com/Discord-Net-Labs/Discord.Net-Labs/pull/138/commits/e414abe3b28f4523a408a0a6e4d878ea5cc7880e

**Comment by MrCakeSlayer** [comment]
@Shadowtail117 do you still need assistance with this?

**Comment by Shadowtail117** [comment]
> @Shadowtail117 do you still need assistance with this?

sorry, forgot I still had the issue open. The bulk overwrite worked like a charm, however it seems that there is some processing delay when altering slash commands. At first it didn't seem to work until I waited an hour. Even then sometimes the commands will give you an error when using them if they have just been added/updated, and then fix themselves a little later. Maybe add this as a warning to the slash command guide?

**Comment by MrCakeSlayer** [comment]
@Shadowtail117 Hello, this is a limit on Discord's end for global commands. They will take up to 1 hour to update, create or delete on servers. If you need quick updates for testing you can use guild commands as they update almost instantly. I believe this used to be in the documentation for creating slash commands however I no longer see it there.

**Comment by Shadowtail117** [comment]
I figured it was an issue with Discord and not Discord.Net, since the commands weren't even sent to the bot, just immediately stopped and an error message given.

I was about to make a PR to address it before I saw yours; for anyone else viewing this issue, the related fix is #160.
