### ISSUE TITLE
Add permission methods to IApplicationCommand

### ISSUE THREAD

**Issue by quinchs** [Discord-Net-Labs/Discord.Net-Labs#151]
# Summary
Modifying permissions is currently only accessible on the rest side. The methods should be implemented into the interface and `SocketApplicationCommand`

**Comment by jgoldshlag** [comment]
This was closed, but I can't seem to figure out how I can modify permissions for a command without using the rest client. Am I missing something?

**Comment by quinchs** [comment]
You use the rest client to get the application commands, currently discord doesnt yet send any application commands via gateway so theres no way to modify them via that
