### ISSUE TITLE
Add cleanContent property to SocketMessage

### ISSUE THREAD

**Issue by ITeMbI4** [Discord-Net-Labs/Discord.Net-Labs#156]
Add `.cleanContent` READ-ONLY property to SocketMessage like in `discord.js`
Description:
The message contents with all mentions replaced by the equivalent text. If mentions cannot be resolved to a name, the relevant mention in the message content will not be converted.

**Comment by emillly-b** [comment]
Does this property remove emojis as well, or only mentions?

**Comment by ITeMbI4** [comment]
Yes, it also affected to emojis

**Comment by quinchs** [comment]
Closed in #174
