### ISSUE TITLE
Events UserJoined and UserLeft not working!

### ISSUE THREAD

**Issue by ITeMbI4** [Discord-Net-Labs/Discord.Net-Labs#158]
![image](https://user-images.githubusercontent.com/46756889/133906727-5ee4945a-fcd7-40b0-84f2-0e2dea8d6b38.png)
![image](https://user-images.githubusercontent.com/46756889/133906733-24ebfc60-752e-4eab-9902-30620bec2ce5.png)

**Comment by SylveonDeko** [comment]
Do you have intents enabled

**Comment by ITeMbI4** [comment]
Yes, I have

**Comment by drobbins329** [comment]
in both the app portal, and on the DiscordSocketConfig?

**Comment by SylveonDeko** [comment]
That or do you have then specified in the client config

**Comment by ITeMbI4** [comment]
![image](https://user-images.githubusercontent.com/46756889/133906775-c6dc2110-577d-44f7-8f55-15e8b3456d5f.png)
![image](https://user-images.githubusercontent.com/46756889/133906788-0da9115d-a8b3-4ff6-8ca6-33e04d56db43.png)

**Comment by SylveonDeko** [comment]
Are you using dependency injection by chance?

**Comment by ITeMbI4** [comment]
It's just fixed when I set `GatewayIntents = GatewayIntents.AllUnprivileged`
