### ISSUE TITLE
SocketGuildUser.Nickname seems to be always null

### ISSUE THREAD

**Issue by NexganGH** [Discord-Net-Labs/Discord.Net-Labs#19]
I don't know if it's a problem with the cache or something else, bu SocketGuildUser.Nickname seems to be always null, despite of the user actually having a nickname in that server.

**Comment by quinchs** [comment]
try your code with the `AlwaysDownloadUsers` set to true and `GatewayIntents = GatewayIntents.All` in the config

**Comment by NexganGH** [comment]
> try your code with the `AlwaysDownloadUsers` set to true and `GatewayIntents = GatewayIntents.All` in the config

My bot doesn't have privileged gateway intents; are you sure they are actually required? I remember fetching the nickname without them.
