### ISSUE TITLE
A way to send a SocketInteraction response without retrieving the original response

### ISSUE THREAD

**Issue by d4n3436** [Discord-Net-Labs/Discord.Net-Labs#21]
Currently when using `SocketInteraction.RespondAsync()`, the method makes 2 API calls:

1. [`POST /interactions/{interaction.id}/{interaction.token}/callback`](https://discord.com/developers/docs/interactions/slash-commands#create-interaction-response), to send a response to the interaction.
2. [`GET /webhooks/{application.id}/{interaction.token}/messages/@original`](https://discord.com/developers/docs/interactions/slash-commands#get-original-interaction-response), to get the original interaction response.

Making an extra API call is expensive if you only want to send the interaction response (e.g. modify the message).

My suggestion is the following:

- Remove the 2nd API call from `RespondAsync()`, or create a new method `SendResponseAsync()` that only sends the response.
- Create a new method `GetOriginalResponseAsync()` that gets the original interaction response.

**Comment by quinchs** [comment]
Il close the issue when the code is up on nuget
