### ISSUE TITLE
Add CleanContent field to IMessage

### ISSUE THREAD

**Issue by quinchs** [Discord-Net-Labs/Discord.Net-Labs#210]
# Summary
Currently `CleanContent` is only supported on `SocketMessage`. It would be neat to have the field available in `RestMessage` and in any other messages inheriting the `IMessage` interface.

**Comment by quinchs** [comment]
@emillly-b

**Comment by emillly-b** [comment]
@quinchs ill knock it out here soon!! You can assign me :)
