### ISSUE TITLE
Random timed out using `SocketGuild.DeleteApplicationCommandsAsync`

### ISSUE THREAD

**Issue by Piripe** [Discord-Net-Labs/Discord.Net-Labs#224]
Sometimes this function makes my program crash, I don't know why.
![Screenshot 2021-10-09 204237](https://user-images.githubusercontent.com/77517308/136670529-353d3501-fe11-4599-a9f0-6b5cca8d559f.png)

I'm using Discord.Net-Labs 3.1.1

**Comment by Anu6is** [comment]
An unhandled exception thrown in an `Async Sub` would crash your program. You shouldn't be using Async Subs unless it's for an event handler. I can't comment specifically on why you get a timeout error, but that or any other exception thrown in `InitCommands` would cause your program to crash.
