### ISSUE TITLE
Unable to use local file directories in embed URL fields.

### ISSUE THREAD

**Issue by csmir** [Discord-Net-Labs/Discord.Net-Labs#226]
Current protocol filter disallows users to use locally stored files in embeds directly. 

``` 
System.InvalidOperationException: Url attachment://logo.png must be include its protocol (either HTTP or HTTPS)
   at Discord.Utils.UrlValidation.Validate(String url) 
```
   
Potential approach/methods to resolve this?

> This same error potentially also exists in other types with URL fields that *can* use local files as well and should be investigated.

**Comment by quinchs** [comment]
Implemented in f2a84298048689cff6ecdd864399b63ef12c2502
