### ISSUE TITLE
CleanContent ping issue

### ISSUE THREAD

**Issue by ITeMbI4** [Discord-Net-Labs/Discord.Net-Labs#228]
CleanContent property returns invalid ping representative to text
From this ping
![image](https://user-images.githubusercontent.com/46756889/136992255-cbfdd7ec-359c-43e3-8a51-38a705e5f909.png)
It returns
`<@!​303446547335610370`

But needs to return `TeMbI4`

With channels ping same issue

**Comment by quinchs** [comment]
@emillly-b
