### ISSUE TITLE
Message.MentionedUsers returns empty list

### ISSUE THREAD

**Issue by ITeMbI4** [Discord-Net-Labs/Discord.Net-Labs#230]
Test it with this
![image](https://user-images.githubusercontent.com/46756889/137005547-9fe36062-28e1-494a-a9c4-6fcbb517a897.png)
Result
![image](https://user-images.githubusercontent.com/46756889/137005653-80dffb53-f5d4-49b3-af19-6a4253e8241d.png)

Please fix this ASAP

**Comment by emillly-b** [comment]
I am able to reproduce this.
