### ISSUE TITLE
Reconnection error

### ISSUE THREAD

**Issue by csmir** [Discord-Net-Labs/Discord.Net-Labs#257]
![View](https://rozen.one/files/VsDebugConsole_XZWjS7q2a0.png)

Caused by the frequent reconnection attempts in [ConnectionManager.cs](https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/release/3.x/src/Discord.Net.WebSocket/ConnectionManager.cs). This error has persisted as long as I have used Discord.NET, are there any options to resolve this?

**Comment by quinchs** [comment]
via Jake#1 (Discord Staff) on the "Discord API" discord: [~April 3]

> Discord is rolling out a software update to our gateways. We anticipate no issues, and have had a canary of the new code running for a while now with no issue. This update introduces only one user visible change.
> 
> Your gateway connection will regularly be asked to reconnect using opcode: https://discordapp.com/developers/docs/topics/gateway#reconnect
> 
> You can simply reconnect and resume as you would tolerate the gateway connection being interrupted via other causes. We are doing this to allow for organic rebalancing of long-lived connections between nodes as nodes eventually start to auto-scale in/out

Via above documentation link:

>Reconnect
>The reconnect event is dispatched when a client should reconnect to the gateway (and resume their existing session, if they have one). This event usually occurs during deploys to migrate sessions gracefully off old hosts.

To put it simply, discord is asking your bot to reconnect to the gateway, theres nothing we can really do on the lib end for that besides reconnect you

**Comment by th0mk** [comment]
Shouldn't the log level be lowered then? If this is expected behavior it shouldn't be logged as an error.
