### ISSUE TITLE
SocketInteraction.FollowupWithFileAsync doesn't match SocketCommandBase's override

### ISSUE THREAD

**Issue by jgoldshlag** [Discord-Net-Labs/Discord.Net-Labs#263]
SocketInteraction:
`public abstract Task<RestFollowupMessage> FollowupWithFileAsync(Stream fileStream, string fileName, string text = null, Embed[] embeds = null, bool isTTS = false, bool ephemeral = false,
            AllowedMentions allowedMentions = null, RequestOptions options = null, MessageComponent component = null, Embed embed = null);`

SocketCommandBase:
`public override async Task<RestFollowupMessage> FollowupWithFileAsync(
            Stream fileStream,
            string text = null,
            string fileName = null,
            Embed[] embeds = null,
            bool isTTS = false,
            bool ephemeral = false,
            AllowedMentions allowedMentions = null,
            RequestOptions options = null,
            MessageComponent component = null,
            Embed embed = null)`

Note the swapping of the text and fileName args, as well as the null default. I was able to get stuff to work, but only by doing this:
`await this.Interaction.FollowupWithFileAsync(s, text: "testing.png", fileName: "actually the text");`

**Comment by quinchs** [comment]
This was fixed in 6092c428dd1a7f5749f073aecfedc79dc4a98a8d

**Comment by quinchs** [comment]
Pushed in 3.2.0
