### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task`1<Discord.IUserMessage> 

### ISSUE THREAD

**Issue by KP0H** [Discord-Net-Labs/Discord.Net-Labs#270]
In general, all my logic works well and I see the correct result. But in the logs I see an error generated by external code.

Is it a problem on my part?

{05:37:05 Command     Discord.Commands.CommandException: Error occurred executing "commandname" for UseTag in UserTag.
 ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Discord.IUserMessage> Discord.UserExtensions.SendMessageAsync(Discord.IUser, System.String, Boolean, Discord.Embed, Discord.RequestOptions, Discord.AllowedMentions)'.
   at Infobot.Handlers.CommandHandlerBase.CommandExecutedAsync(Optional`1 command, ICommandContext context, IResult result)
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   --- End of inner exception stack trace ---}
    Exception: {"Error occurred executing \"kurator\" for KP0H™#8837 in @KP0H™#8837."}
    Message: null
    Severity: Error
    Source: "Command"
    
    
msg.Exception.InnerException
{"Method not found: 'System.Threading.Tasks.Task`1<Discord.IUserMessage> Discord.UserExtensions.SendMessageAsync(Discord.IUser, System.String, Boolean, Discord.Embed, Discord.RequestOptions, Discord.AllowedMentions)'."}
    ClassName: null
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233069
    HelpLink: null
    InnerException: null
    MemberName: null
    Message: "Method not found: 'System.Threading.Tasks.Task`1<Discord.IUserMessage> Discord.UserExtensions.SendMessageAsync(Discord.IUser, System.String, Boolean, Discord.Embed, Discord.RequestOptions, Discord.AllowedMentions)'."
    Signature: null
    Source: "Infobot"
    StackTrace: "   at Infobot.Handlers.CommandHandlerBase.CommandExecutedAsync(Optional`1 command, ICommandContext context, IResult result) in *blablabla*\\Handlers\\CommandHandlerBase.cs:line 120\r\n   at Discord.EventExtensions.<InvokeAsync>d__3`3.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()"
    TargetSite: {System.Threading.Tasks.Task CommandExecutedAsync(Discord.Optional`1[Discord.Commands.CommandInfo], Discord.Commands.ICommandContext, Discord.Commands.IResult)}

**Comment by quinchs** [comment]
The error `Method not found` means somthing is looking for that method that doesn't exist anymore because it has changed. You must have a package installed looking for this method.

**Comment by Liege72** [comment]
Could you send the function that line 120 is in?

**Comment by KP0H** [comment]
83  public Task CommandExecutedAsync(Optional<CommandInfo> command, ICommandContext context, IResult result)
84 {
  //logic ...
118  context.Channel.SendMessageAsync($"***").Wait();
119  return Task.CompletedTask;
120 }

With regular Discord.Net this code base class work fine. Problem after update to Discord.Net Labs

Also this code should be unreacheble in case of IResult result.IsSuccess = true.

**Comment by d4n3436** [comment]
That exception happens when the library can't find the method with that exact signature. Make sure you're using the package `Discord.Net.Labs.Commands` (not `Discord.Net.Commands`), and make sure you have all Discord.Net Labs packages up to date.
