### ISSUE TITLE
`SocketGuild.Users` only gets users that are chatting

### ISSUE THREAD

**Issue by kram-tm** [Discord-Net-Labs/Discord.Net-Labs#275]
![2BDBF072-B486-4912-978B-0A69AE825C8C](https://user-images.githubusercontent.com/34284981/140947188-dc363424-eab7-42bf-9dd1-538c6336fe02.jpeg)

`Guild.Users` only gets users that have sent at least one message while the bot was online. This doesn't seem to be a problem with Discord.Net.
Code:

```cs
[Command("getmembers")]
public async Task GetMembers()
{
  List<string> users = new List<string>();
  foreach(SocketGuildUser user in Context.Guild.Users)
  {
    users.Add(user.Username);
  }
  await ReplyAsync(String.Join(", ",users));
}
```

I originally wanted to get every user who has the specified role, but I got the same results. Is there an extra step I'm missing or am I just dumb?

**Comment by quinchs** [comment]
The reason for this is that socket related entities are cached, if you want to get all the users you need to download them from the gateway. One simple way of doing this is setting `AlwaysDownloadUsers` to true in your socket config

**Comment by kram-tm** [comment]
Works. Thank you!
