### ISSUE TITLE
Slash Command Timeout error

### ISSUE THREAD

**Issue by bloody-green-tea** [Discord-Net-Labs/Discord.Net-Labs#286]
Why do i have to answer the slash command in 3 seconds?
i can't debugging or develop some slash commands with response limit in 3 seconds.

test code:
```cs
private static Task ClientOnSlashCommandExecuted(SocketSlashCommand arg) {
  Console.WriteLine((DateTime.UtcNow - arg.CreatedAt).TotalSeconds);
  arg.DeferAsync();
  return Task.CompletedTask;
}
```

result: 4.8949309

**Comment by quinchs** [comment]
Seems like your local clock is out of sync, I'll add a way to not use the local clock soon
