### ISSUE TITLE
GuildScheduledEvent doesn't run 

### ISSUE THREAD

**Issue by ITeMbI4** [Discord-Net-Labs/Discord.Net-Labs#287]
Get this error in console
![image](https://user-images.githubusercontent.com/46756889/142685633-436954ba-9695-4869-b766-411f2d8527a0.png)

**Comment by quinchs** [comment]
Those events arn't added as discord is deprecating them soon, il add them in a bit just cuz tho

**Comment by quinchs** [comment]
Implemented in 3.3.2
