### ISSUE TITLE
FollowupWithFile with components doesn't include components

### ISSUE THREAD

**Issue by jgoldshlag** [Discord-Net-Labs/Discord.Net-Labs#288]
Not sure if this is actually a discord issue, but I can't seem to get components to show up when using SocketInteraction::FollowupWithFIle.

This doesn't work:
await Interaction.FollowupWithFileAsync(s, "gac_map.png", text: "123", component: componentBuilder.Build());

And this works fine:
await Interaction.FollowupWithFileAsync(s, "gac_map.png");
await Interaction.FollowupAsync("123", component: componentBuilder.Build());

**Comment by quinchs** [comment]
What type of interaction are you using? ex buttons, slash, context menu, etc

**Comment by jgoldshlag** [comment]
Slash, and I did defer the interaction initially (ephemerally) (though I just tested, and ephemeral or not I have the same issue)
