### ISSUE TITLE
Add the ability to get user by name/discrim

### ISSUE THREAD

**Issue by SylveonDeko** [Discord-Net-Labs/Discord.Net-Labs#290]
I feel like this will be useful in cases where you aren't able to get the ID of a member, for example a reason in audit logs that just says the username, for example in my bot it says when banning: Sylveon#0001 | reason here

**Comment by quinchs** [comment]
This isn't possible if the user isn't in a guild.

If they are in a guild you can use `SearchUsersAsync("user#1234")`.
