### ISSUE TITLE
Can't create Threads in News (Announcement) channels.

### ISSUE THREAD

**Issue by aggiczy** [Discord-Net-Labs/Discord.Net-Labs#296]
**Hi there!**

I've got this error message when I try to create a thread in a News Channel:
```csharp
System.NullReferenceException: Object reference not set to an instance of an object.
```

My method:
```csharp
(Context.Channel as SocketNewsChannel).CreateThreadAsync("test");
```

What is the problem in this? Can you fix it please?

**Thanks,**
***Aki26 GamePlay#3982***

**Comment by quinchs** [comment]
Is there a stack trace with the exception?

**Comment by aggiczy** [comment]
> Is there a stack trace with the exception?

Sorry but I don't know exactly what is stack trace. Maybe this?:
```csharp
System.NullReferenceException: Object reference not set to an instance of an object.
   at Submission#0.<<Initialize>>d__0.MoveNext()
```

**Comment by quinchs** [comment]
The reason for the excpetion is that `Context.Channel` is not a `SocketNewsChannel`, therfor casting it yields null.

**Comment by aggiczy** [comment]
But with ITextChannel I get the same error message.

Edit: With ITextChannel I don't get error but it don't create the thread.

**Comment by aggiczy** [comment]
So my question: How can I create threads in a News/Announcement channel?

**Comment by quinchs** [comment]
~Discord doesn't seem to allow bots to create threads in news~
![image](https://user-images.githubusercontent.com/49576606/143785707-1ef7ec85-ba47-47b6-a05f-aee7ce327505.png)

**Comment by quinchs** [comment]
Disregard, as pointed out by @NovaFox161 you need to specify `ThreadType.NewsThread` when creating your thread. An example would be:
```cs
var chan = client.GetGuild(guildId).GetTextChannel(newsChannelId);
await chan.CreateThreadAsync("test", ThreadType.NewsThread);
```

**Comment by Aki26-GamePlay** [comment]
Thanks. But why this is not automatic?
