### ISSUE TITLE
GuildScheduledEventStarted and GuildScheduledEventCompleted dont trigger

### ISSUE THREAD

**Issue by daanvandenhoek** [Discord-Net-Labs/Discord.Net-Labs#302]
Hi,

I made a discord bot that uses GuildScheduledEventStarted and GuildScheduledEventCompleted but they dont seem to trigger.

Assignment
```
 _client.GuildScheduledEventStarted += GuildEventStatusChanged;
 _client.GuildScheduledEventCompleted += GuildEventStatusChanged;
```

Function
 ```
private Task GuildEventStatusChanged(SocketGuildEvent guildEvent)
    {
        Console.WriteLine(new LogMessage(LogSeverity.Debug, "GuildEventStatusChanged", $"Guild Event Changed: {guildEvent}").ToString());

        return Task.CompletedTask;
    }
```

The function GuildEventStatusChanged is never triggered

**Comment by Cenngo** [comment]
Are you using the `GUILD_SCHEDULED_EVENTS` intent

**Comment by daanvandenhoek** [comment]
I am not but because the GuildScheduledEventCancelled works so I thought it wasn't needed. That did fix the problem! Thanks!
