### ISSUE TITLE
SocketVoiceChannel options are created as generic mentionables in Interaction service

### ISSUE THREAD

**Issue by CottageDwellingCat** [Discord-Net-Labs/Discord.Net-Labs#305]
the command
```cs
[SlashCommand("channel-type", "channel types")]
public async Task ChannelType(
	[Summary("channel", "the channel")]
	SocketVoiceChannel channel)
{
	await Context.Interaction.RespondAsync(channel.Name);
}
```
gets registered in discord with the mentionable type; appearing as
![image](https://user-images.githubusercontent.com/80918250/143612432-1f5a2658-a055-4431-afb3-dbbe500fc569.png)
Running the command results in the interaction created log being sent, but nothing else. My logLevel is debug on the service and client.

**Comment by quinchs** [comment]
@Cenngo Is there any automated `ChannelType` delimiter in the parameter builders? It would make sense to do interface checks like 
```cs
if(type is IVoiceChannel)
{
    channelTypes.Add(ChannelType.Voice);
}
```

**Comment by Cenngo** [comment]
There is, but appearently it is not working. Let me check.
