### ISSUE TITLE
Can't execute SlashCommands with DiscordShardedClient.

### ISSUE THREAD

**Issue by aggiczy** [Discord-Net-Labs/Discord.Net-Labs#313]
**Hi there.**

I can't execute a SlashCommand with a Sharded client because when I try to create a SocketInteractionContext it only accept the DiscordSocketClient type. ![Screenshot](https://user-images.githubusercontent.com/64480571/143662088-149248c1-d2c3-40ae-9707-c0d6474231a1.png)

***How can I execute slash commands with a sharded client?***

**Thanks,**
***Aki26 GamePlay***

**Comment by exsersewo** [comment]
Try [ShardedInteractionContext](https://discord-net-labs.com/api/Discord.Interactions.ShardedInteractionContext.html?q=Shardedinteractioncontext) instead of SocketInteractionContext

**Comment by aggiczy** [comment]
Oh, right.  It's working.  Thanks.
