### ISSUE TITLE
Manual registration of global module 

### ISSUE THREAD

**Issue by Misha12** [Discord-Net-Labs/Discord.Net-Labs#319]
InteractionService have method `AddCommandsToGuildAsync` and `AddModulesToGuildAsync`. But if i want register module or command globally to allow usage in DMs and not register modules that require guild i haven't got method for this. How can i do this?

**Comment by quinchs** [comment]
```cs
service.RegisterCommandsGloballyAsync();
```

Taken from the [Docs](https://discord-net-labs.com/guides/interactions_framework/intro.html#registering-commands-to-discord)

**Comment by Misha12** [comment]
I know, but what if i don't want register some modules for hide unavailable commands purposes?

Example:
I've got 3 modules (A, B, C) and modules A and B will be registered in guild because they implementation requires guild. But module C don't require guild and could be called from DMs. 

I can use `RegisterCommandsGloballyAsync` and `DontAutoRegisterAttribute` and after this call `AddModulesToGuildAsync` for registration of the remaing modules. But i think that is hack and InteractionService should have methods `AddCommandsGloballyAsync` and `AddModulesGloballyAsync` and support `ignoreMissing` parameter.

**Comment by Cenngo** [comment]
You are right, this was brought to my attention by @FeroxFoxxo on the day of roll-out but i didnt have time to implement it. I'll add a seperate method for registering global commands this way.
