### ISSUE TITLE
Error from TypeConverters not fire SlashCommandExecuted event

### ISSUE THREAD

**Issue by Misha12** [Discord-Net-Labs/Discord.Net-Labs#321]
After execution of some slash command is fired event SlashCommandExecuted. But when execution fails in TypeConverter (TypeConverter returns `TypeConverterResult.FromError(...)`) result is provided only via result of `ExecuteCommandAsync` but not fired event. I think that is bug and problematic handle this situations.

**Comment by Liege72** [comment]
See #322

**Comment by Cenngo** [comment]
> After execution of some slash command is fired event SlashCommandExecuted. But when execution fails in TypeConverter (TypeConverter returns `TypeConverterResult.FromError(...)`) result is provided only via result of `ExecuteCommandAsync` but not fired event. I think that is bug and problematic handle this situations.

This should be fixed on #314. Are you using the latest version?

**Comment by Misha12** [comment]
Sorry, my bad. I had 3.4.2. I updated to 3.4.6 and problem is fixed. Thanks
