### ISSUE TITLE
Error-handling is not working

### ISSUE THREAD

**Issue by aggiczy** [Discord-Net-Labs/Discord.Net-Labs#331]
**Hi there,**

The error handling (like RequireUserPermission's error if the user not have the permission) is not working. I checked v3.4.0 and in that version it's working properly but in v3.4.7 it's not.
*Please fix it!*

**Thanks,**
***Aki26 GamePlay***

**Comment by Cenngo** [comment]
You need to expand on "not working".

Are you saying that failed preconditions dont invoke the "CommandExecuted" event?

**Comment by aggiczy** [comment]
I'm saying that when I for example run a command and I have no permission for this command, the failed precondition is null.

**Comment by Cenngo** [comment]
In my testing i didnt encounter any unintended behaviour, failed preconditions seem to return a failed result as expected. Can you provide me with the necessary steps to reproduce this?

**Comment by aggiczy** [comment]
I just solve the problem with do the error handling not in the ExecuteCommandAsync Task, but in the _commands.CommandExecuted event.
*Thanks for the help, and sorry for the long respond-time.*
