### ISSUE TITLE
Incorrect number of autocomplete choices

### ISSUE THREAD

**Issue by nev-r** [Discord-Net-Labs/Discord.Net-Labs#332]
https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/c5b8d07378c7a8f277d5d7df1035809d6b2603e8/src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteraction.cs#L83

25 choices are supported. autocomplete options follows the [Application Command Option Structure](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure)

**Comment by EndGameGl** [comment]
Adding to the report: exact bug location
InteractionHelper.cs
public static Task SendAutocompleteResultAsync
Preconditions.AtMost(result.Count<AutocompleteResult>(), 20, nameof (result), "A maximum of 20 choices are allowed!");
