### ISSUE TITLE
GatewayIntents.None not letting through "passthrough" events

### ISSUE THREAD

**Issue by TheStachelfisch** [Discord-Net-Labs/Discord.Net-Labs#345]
When specifying `GatewayIntents = GatewayIntents.None` in a `DiscordSocketConfig` then "passthrough" events as specified in the Discord documentation are not passed through. Those events mainly include the `INTERACTION_CREATE` event

When specifying `GatewayIntents = GatewayIntents.All` the `INTERACTION_CREATE` event is still let through, same with `GatewayIntents = GatewayIntents.Guilds`

The Discord docs state:
> Any events not defined in an intent are considered "passthrough" and will always be sent to you.
The `INTERACTION_CREATE` is included by this and should therefore be always sent regardless of what intents where specified.

**Comment by CottageDwellingCat** [comment]
Can you try setting your log level to debug and checking to see if the event is received by your client?

**Comment by TheStachelfisch** [comment]
The interaction is indeed received. The event is just not called

```
Debug -> Gateway : Received Dispatch (INTERACTION_CREATE) 
Verbose -> Rest : GET channels/758740887412408331: 163,86 ms 
Debug -> Gateway : Unsynced Guild (INTERACTION_CREATE Guild=758739587144613979).
```

**Comment by quinchs** [comment]
Thats becuase the guild isn't known, unsynced. Thats required for the event.

**Comment by TheStachelfisch** [comment]
How would I go about syncing it then?

**Comment by quinchs** [comment]
You would need the Guilds intent

**Comment by TheStachelfisch** [comment]
Ok thanks
