### ISSUE TITLE
Some discord users are not valid SocketGuildUsers in DNL 3.4.0 and 3.4.9

### ISSUE THREAD

**Issue by JerzyKruszewski** [Discord-Net-Labs/Discord.Net-Labs#366]
Some of the users on my server can't be recognized by the bot as `SocketGuildUser`.
Commands return `IResult`: ObjectNotFound: User not found.
The issue only applies to certain users and only exists in Discord.Net.Labs (Changing back to Discord.Net 2.4.0 fixed this issue).

Example command:
```
    [Command("Status")]
    public async Task CheckStatus(SocketGuildUser user = null)
    {
        if (user is null)
        {
            user = Context.User as SocketGuildUser;
        }
        SocketGuild guild = Context.Guild;
        GuildConfig config = new GuildConfigs(guild.Id, _storage).GetGuildConfig();
        AlertsHandler alerts = new AlertsHandler(config);
        UserAccounts accounts = new UserAccounts(guild.Id, _storage);
        UserAccount account = accounts.GetUserAccount(user.Id);

        accounts.DeleteExpiredWarnings(account);

        string message = GetStatusMessage(user, config, alerts, account);

        await Context.Channel.SendMessageAsync(message);
    }
    
// Execution: %status {user ping or id}
// Output: ObjectNotFound User not found.
```

**Comment by SylveonDeko** [comment]
You need to specify intents in your socketconfig

**Comment by akaJuliaan** [comment]
You should also enable the GUILD_MEMBERS intent in the developer portal

![grafik](https://user-images.githubusercontent.com/54598714/145684924-88c367af-8a8a-4be3-a8f3-5280fca37517.png)

**Comment by JerzyKruszewski** [comment]
@YunoGasai67 @Komischerboy 
Thank you! It solved my issue. I have enabled GUILD_MEMBERS intent in the developer portal, but didn't realize that I need to specify them in code.
