### ISSUE TITLE
CommandExecuted event not firing for several errors

### ISSUE THREAD

**Issue by BowDown097** [Discord-Net-Labs/Discord.Net-Labs#376]
I do my error handling with the CommandExecuted event, and I noticed that after a recent update this event does not fire in many scenarios, in my case when a command errors with BadArgCount, ParseFailed, or ObjectNotFound (and I'm sure more, those are just the only ones I covered that didn't work). UnmetPrecondition, Unsuccessful, and one of my own error types fire this event perfectly fine. Was this part of an intentional change? If so, what's the solution?

**Comment by Kerillian** [comment]
I've noticed this too on the most recent nightly build for base Discord.Net repo. I reply with the help for the command if the user doesn't provide proper arguments for it, but ever since updating to the nightly builds from v2.4.0 that feature completely stopped working.

**Comment by BowDown097** [comment]
Looks like it broke with changes to the ExecuteAsync method in version 3.4.3. Downgrading the library to 3.4.2 fixes the problem for me.

**Comment by quinchs** [comment]
cc @Cenngo

**Comment by Cenngo** [comment]
wasnt this fixed on #384

**Comment by quinchs** [comment]
yep and is fixed in 3.6.0
