### ISSUE TITLE
Something wrong with GuildMemberUpdated

### ISSUE THREAD

**Issue by ITeMbI4** [Discord-Net-Labs/Discord.Net-Labs#379]
Before 3.5.0 this event was working fine.

Now, I get this:
![image](https://user-images.githubusercontent.com/46756889/146531468-32f61a37-688b-454b-9f78-fb4c3a8d3e86.png)

With this code:
![image](https://user-images.githubusercontent.com/46756889/146531605-d5281311-ec57-416b-8dab-fcf83b4bbff0.png)

**Comment by quinchs** [comment]
Was the user in the cache when this event was triggered?

**Comment by ITeMbI4** [comment]
Yep, I run `DownloadUsersAsync()` before it.

**Comment by ITeMbI4** [comment]
Also in code I'm using `CachedOldUser.GetOrDownloadAsync()`

**Comment by quinchs** [comment]
This has been fixed in https://github.com/Discord-Net-Labs/Discord.Net-Labs/commit/08beead775cdacea15b9935c60a9d70947d3f1e9
