### ISSUE TITLE
NRE in UserLeft event

### ISSUE THREAD

**Issue by ITeMbI4** [Discord-Net-Labs/Discord.Net-Labs#380]
Very rare, but I get NRE in this event
![image](https://user-images.githubusercontent.com/46756889/146547780-7f4edc7b-2ad3-4cd3-a3f5-de65665105c5.png)

**Comment by csmir** [comment]
Can you include the code on this?

**Comment by quinchs** [comment]
This exception is in your handler - as stated by the "A UserLeft handler has thrown an unhandled exception". Can you provide the code in the handler?

**Comment by ITeMbI4** [comment]
I think there was my issue, because I don't get NRE anymore.
