### ISSUE TITLE
Timestamp tags

### ISSUE THREAD

**Issue by Thundermaker300** [Discord-Net-Labs/Discord.Net-Labs#40]
Discord has added support for timestamp tags by typing `<t:epoch timestamp here:style here>`  (https://discord.com/developers/docs/reference#message-formatting-timestamp-styles), however there is no support for finding these via tags.

(Should also be noted that the displayed time changes to match the viewer's timezone, and the "R" style [relative, eg "20 minutes ago"] supports the display changing without the message being edited)

![image](https://user-images.githubusercontent.com/24486646/125173140-a59a7900-e18b-11eb-9420-962a0616e1cc.png)
![image](https://user-images.githubusercontent.com/24486646/125173152-bf3bc080-e18b-11eb-8151-9053daf25032.png)

**Comment by quinchs** [comment]
Il close the issue once its live on nuget.
