### ISSUE TITLE
client.GetUser() returning null on valid args

### ISSUE THREAD

**Issue by Cephy314** [Discord-Net-Labs/Discord.Net-Labs#42]
`var user = client.GetUser(name, discriminator);
            if (user != null)
            {
                await context.Response.SendResponseAsync("true");
                return;
            }
`
Using Discord.Net 2.4 this works fine.  Using Labs it fails and returns null.

**Comment by quinchs** [comment]
![image](https://user-images.githubusercontent.com/49576606/126013511-3b15167f-e098-4ca0-b2cf-ed1fe34cd013.png)

Try adding `GatewayIntents = GatewayIntents.All` and `AlwaysDownloadUsers = true,` in your client config. I have no issues with running the above code
