### ISSUE TITLE
Withbutton method does not handle exception when using buttonbuilder

### ISSUE THREAD

**Issue by Qialet** [Discord-Net-Labs/Discord.Net-Labs#430]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When using the assembled buttonbuilder manually, the method does not check the styles, as it is done if the button is assembled through the method.

If it's easier, if you assemble the button through the method, then the style is checked, if you assemble it through the button builder, the style is not checked.

### Version

3.6.1 labs

### Logs

![image](https://user-images.githubusercontent.com/56882712/149686083-418ca74c-54bf-4c35-982d-f33044c756bc.png)

### Sample

```
var ButtonRight = new ButtonBuilder { Label = "testLabel", CustomId = $"TestId"};
var Comp = new ComponentBuilder().WithButton(ButtonRight);

try
{
    await Context.Channel.SendMessageAsync("", false, null, components: Comp.Build());
}
catch (Discord.Net.HttpException ex)
{
    Console.WriteLine(ex.Errors);
}
```

**Comment by CottageDwellingCat** [comment]
this is resolved in #429
