### ISSUE TITLE
ModifyCommandPermissions Throws error 50035

### ISSUE THREAD

**Issue by Math0424** [Discord-Net-Labs/Discord.Net-Labs#45]
When using **RestGuildCommand.ModifyCommandPermissions** to change slash command permissions the error 'The server responded with error 50035: Invalid Form Body' will be thrown

[The documentation](https://discord.com/developers/docs/interactions/slash-commands#permissions)

**Comment by gehongyan** [comment]
The same exception when calling **`ModifyCommandPermissions`** here.

**Comment by quinchs** [comment]
can you verify that the most recent lab version on nuget has this issue?

**Comment by Blizeri** [comment]
Same here 'The server responded with error 50035: Invalid Form Body'. Using latest nuget.

**Comment by quinchs** [comment]
Will close when patch is live on nuget
