### ISSUE TITLE
Slash Command Implementation Sample

### ISSUE THREAD

**Issue by sergioliveira07** [Discord-Net-Labs/Discord.Net-Labs#54]
Can we have an example of an implementation of discord Slash commands? I can't find any in repo.

**Comment by MrCakeSlayer** [comment]
There's documentation linked at the bottom of the main README file. you can view the guides here for slash commands: https://github.com/Discord-Net-Labs/Discord.Net-Labs/tree/Interactions/docs/guides/slash-commands
