### ISSUE TITLE
"ComponentBuilder.WithButton" takes customID as a required param but still accepts a Url despite not being allowed to use both.

### ISSUE THREAD

**Issue by Zeiin** [Discord-Net-Labs/Discord.Net-Labs#56]
https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/333f36eeb8823614e5c33cbaa2a4ee33a38d605d/src/Discord.Net.Core/Entities/Interactions/Message%20Components/ComponentBuilder.cs#L137

Changing CustomID to be optional and assume the writer knows the constaint there seems like a solid solution, since an error is thrown if you pass both together. There are a few other solutions you could employ, so I didn't want to just commit this change myself.

Alternatively -- Remove URL from this method entirely. Using a link would require no customID and a specific style, so it would remove some ambiguity if you just left links out of this.

Also, in the same class, is this not redundent?
https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/333f36eeb8823614e5c33cbaa2a4ee33a38d605d/src/Discord.Net.Core/Entities/Interactions/Message%20Components/ComponentBuilder.cs#L160

when this exists?

https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/333f36eeb8823614e5c33cbaa2a4ee33a38d605d/src/Discord.Net.Core/Entities/Interactions/Message%20Components/ComponentBuilder.cs#L169

**Comment by INikonI** [comment]
Redundent methods removed in my recent commits. About customId, you can just set it to `null` or use `CreateLinkButton` method?

**Comment by Zeiin** [comment]
That is a workaround, but what's the point of leaving it as a required parameter if you're going to utilize that workaround?

**Comment by INikonI** [comment]
Hmm, ok, considering discord docs and the fact that this is really a workaround, it will be change to optional argument in my next commits. (if it will be merged .-.)

**Comment by INikonI** [comment]
Resolved in #58 -> 61527f68efeacabaec4723f06c1aa45d2a2a215a
