### ISSUE TITLE
Embed[] alongside Embed

### ISSUE THREAD

**Issue by Zeiin** [Discord-Net-Labs/Discord.Net-Labs#67]
In a recently commit, RespondAsync and FollowupAsync lost their single embed overloads in favor of a single method that takes an array of embeds. This is a pretty code breaking change for many people, so I propose that instead of adding an overload or something adjacent, we take the current methods and add an optional single embed param.

Logically the flow is fairly simple. We would be to check if the embeds param is null, and if so check if the embed param isn't null. In the scenario where both of these is true, set embeds to be an array with that single embed and leave the rest of the code unchanged.

Now instead of leaving it up to the user to write new[]{myEmbed.build()}, they can just clarify embed: or embeds: as needed.

I've made a branch in my fork with this code change commit already if anyone would like to take a look and give opinions. I'm not saying this is necessary or something we need, but I think it's worth considering and getting input on.

The code change in my new branch can be found here:
https://github.com/Zeiin/Discord.Net-Labs/commit/88a8e95816a862c5fe5d66922139b25fbd46f459

**Comment by quinchs** [comment]
I think this is a viable option for sending multiple embeds, could you open a PR
