### ISSUE TITLE
SendMessageAsync and SendFileAsync should match RespondAsync and FollowupAsync in primarily taking an embed array since single embed properties are deprecated

### ISSUE THREAD

**Issue by Zeiin** [Discord-Net-Labs/Discord.Net-Labs#68]
SendMessageAsync currently doesn't take an array of embeds, rather just one. Discord's docs mention that messages can (and should) use an embed array instead.

I've started working on this change -- if anyone wants to review that I've done it correctly before I continue and do SendFileAsync. 
Please note that currently to keep in line with my previous commit/suggestion, I also have an optional single embed param added to the end of the new method signatures, but those can be removed easily if that other suggestion is decided against.

Review the current code changes here:
https://github.com/Zeiin/Discord.Net-Labs/commit/1ef7e083cabb5c7b529782a2cd31c11844ad9a71

**Comment by quinchs** [comment]
Looks good, Could you open a PR?

**Comment by Zeiin** [comment]
Let me first get the SendFile methods up to date too.
