### ISSUE TITLE
Respond an interaction with DeferredChannelMessageWithSource

### ISSUE THREAD

**Issue by d4n3436** [Discord-Net-Labs/Discord.Net-Labs#85]
The latest commits added `SocketInteraction.ModifyOriginalResponseAsync()` to `SocketInteraction`, which is necessary to update a message that comes from a deferred interaction with callback type 5 (`DeferredChannelMessageWithSource`).

Unfortunately, the `type` parameter was removed from `SocketInteraction.RespondAsync()`, making impossible to properly update a message using this callback type.

This issue should be easy to fix. Maybe adding a bool to `DeferAsync()` that determines whether to use `DeferredUpdateMessage` or `DeferredChannelMessageWithSource`?

Edit: It seems that `SocketSlashCommand.DeferAsync()` [uses](https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/release/2.x/src/Discord.Net.WebSocket/Entities/Interaction/Slash%20Commands/SocketSlashCommand.cs#L159) `DeferredChannelMessageWithSource`
..but `SocketMessageComponent.DeferAsync()` [uses ](https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/release/2.x/src/Discord.Net.WebSocket/Entities/Interaction/Message%20Components/SocketMessageComponent.cs#L236) `DeferredUpdateMessage` 🤔 

In any case, there should be a way to use both types.

**Comment by quinchs** [comment]
Take a look at the solution, let me know what you think.

**Comment by Rutherther** [comment]
I don't think that ephemeral = true has any effect for `DeferredUpdateMessage`, if that's right, I would think that better solution would be to put `DeferredChannelMessageWithSource` to `DeferAsync` and make a method for `DeferredUpdateMessage` without taking ephemeral parameter. That way there wouldn't be an argument that does nothing. That would also go with that DeferAsync does the same thing for both components and slash commands.

Just a suggestion, fell free to disagree.

**Comment by quinchs** [comment]
Have you seen [this](https://github.com/Discord-Net-Labs/Discord.Net-Labs/commit/afd9600af2ed4846d1c04b54a5b7eec257940086#diff-839e69da981fc44bb0af003590b88a20c4e97ae538c64b32c0e6b5a91f104837R233) function?

**Comment by Rutherther** [comment]
Yes I have and what I meant by my comment was that this function behavior would switch with `DeferAsync` (and ofc would have to be renamed appropriately)

**Comment by d4n3436** [comment]
@quinchs I tested the changes and I was getting `HttpException` because the `Embed` property in `MessageProperties` was being completely ignored. I fixed this and now the loading message is appearing.

**Comment by d4n3436** [comment]
There are 3 methods that are ignoring the `Embed` property because of the change to embed arrays.
I will make a PR to solve this and to fix the embed check.
