### ISSUE TITLE
SocketInteraction Defer ephemerally

### ISSUE THREAD

**Issue by Rutherther** [Discord-Net-Labs/Discord.Net-Labs#88]
There is no option to `SocketInteraction.DeferAsync` ephemerally right now, even though Discord supports it (at least for slash commands). 

The problem is that right now to respond ephemerally after 3 second timeout, you must send regular response before the timeout and then a followup for the real response. That creates two messages unnecessarily. If `DeferAsync` supported ephemeral, it could be done only with one message (loading that is then replaced).

This should be fairly easy to implement, I could do a PR if you confirm to me that changing the method to `DeferAsync(bool ephemeral = false, RequestOptions options = null)` is okay.

Just a note, this issue is about the same method as in #85, so it could be efficient to implement both issues at once.

**Comment by Rutherther** [comment]
I've tested it with message components and Defer with type `DeferredChannelMessageWithSource` can also be sent ephemerally.

I am thinking that new option to `DiscordSocketConfig` could be added to set it up so `AlwaysAcknowledgeInteractions` could acknowledge either ephemerally or non ephemerally, what do you think?

**Comment by quinchs** [comment]
Support has been added, Il close this issue once its live
